blog/urls.py
from django.urls import path
from .views import blog_view, BlogDetailView

app_name = 'blog'
urlpatterns = [
    path('', blog_view, name='blog-list'),
    path('<int:pk>/<str:title>', BlogDetailView.as_view(), name='blog-detail'),
]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from config import settings
from django.urls import path, include

urlpatterns = [
    path("", include('core.urls')),
    path("account/", include('account.urls')),
    path("travel/", include('travel.urls')),
    path("blog/", include('blog.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travel/urls.py
from django.urls import path
from .views import hotel_list_view, HotelDetailView, tour_list_view, TourDetailView, visa_list_view, flight_list_view

app_name = 'travel'
urlpatterns = [
    path('hotels/', hotel_list_view, name='hotel-list'),
    path('hotels/<int:pk>/<str:title>', HotelDetailView.as_view(), name='hotel-detail'),
    path('tours/', tour_list_view, name='tour-list'),
    path('tours/<int:pk>/<str:title>', TourDetailView.as_view(), name='tour-detail'),
    path('visa/', visa_list_view, name='visa-list'),
    path('flight/', flight_list_view, name='flight-list'),
    path('flight/', flight_list_view, name='flight-list'),
]

travel/models.py
from django.db import models
from django.urls import reverse
from django.utils.html import format_html
from django.utils.translation import gettext_lazy as _

from travel.managers import TourManager, HotelManager, FlightManager, ProviderManager


# Create your models here.
class TravelCategory(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('category'))
    description = models.TextField(verbose_name=_('description'))
    image = models.ImageField(null=True, blank=True, upload_to='categories/travel/', verbose_name=_('تصویر'))
    for_hotel = models.BooleanField(default=True, verbose_name=_('For Hotel'))
    for_tour = models.BooleanField(default=True, verbose_name=_('For tour'))
    for_flight = models.BooleanField(default=True, verbose_name=_('For flight'))
    for_visa = models.BooleanField(default=True, verbose_name=_('For flight'))
    parent = models.ForeignKey(
        'self',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='subcategories',
        verbose_name=_('parent')
    )

    class Meta:
        verbose_name = _('دسته بندی')
        verbose_name_plural = _('5. دسته بندی ها')

    def __str__(self):
        return self.name


class FlightTicket(models.Model):
    TRAVEL_TYPE_CHOICES = [
        ('ECONOMY', 'اکونومی'),
        ('PREMIUM_ECONOMY', 'پرمیوم اکونومی'),
        ('BUSINESS', 'بیزینس'),
        ('PREMIUM_BUSINESS', 'پرمیوم بیزینس'),
        ('FIRST', 'فرست'),
        ('PREMIUM_FIRST', 'پرمیوم فرست')
    ]

    airline = models.CharField(max_length=100, verbose_name=_("شرکت هواپیمایی"))
    airline_logo = models.ImageField(upload_to='airline_logos/', null=True, blank=True,
                                     verbose_name=_("لوگوی شرکت هواپیمایی"))
    flight_number = models.CharField(max_length=100, verbose_name=_("شماره پرواز"))
    travel_type = models.CharField(max_length=20, choices=TRAVEL_TYPE_CHOICES, verbose_name=_("نوع سفر"))
    origin = models.CharField(max_length=100, verbose_name=_("مبدا"))
    destination = models.CharField(max_length=100, verbose_name=_("مقصد"))
    departure_date = models.DateTimeField(verbose_name=_("تاریخ پرواز"))
    arrival_date = models.DateTimeField(verbose_name=_("تاریخ ورود"))
    price_adult = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=_("قیمت بزرگسال"))
    price_child = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=_("قیمت کودک"))
    price_infant = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=_("قیمت نوزاد"))
    currency = models.CharField(max_length=20, null=True, verbose_name=_('واحد پول'))
    active = models.BooleanField(verbose_name=_('فعال/غیرفعال'), default=True)
    keywords = models.TextField(verbose_name=_('کلمات کلیدی'), null=True, blank=True)
    categories = models.ManyToManyField(
        to=TravelCategory,
        related_name='flight_categories',
        verbose_name=_('categories')

    )

    class Meta:
        verbose_name = 'پرواز'
        verbose_name_plural = '1. پرواز ها'

    objects = FlightManager()

    def __str__(self):
        return f"{self.airline} از {self.origin} به {self.destination}"


class Hotel(models.Model):
    image = models.ImageField(verbose_name=_('تصویر اصلی'), upload_to='hotels/')
    image_cover = models.ImageField(verbose_name=_('تصویر کاور'), upload_to='hotels/', null=True, blank=True)
    # ai_summary = models.TextField(verbose_name=_('خلاصه هوش مصنوعی'), null=True, blank=True)
    title = models.CharField(verbose_name=_('عنوان هتل'), max_length=200)
    location = models.CharField(verbose_name=_('لوکیشن'), max_length=200)
    location_url = models.CharField(verbose_name=_('آدرس گوگل مپ'), null=True, max_length=200)
    location_img = models.ImageField(verbose_name=_('تصویر لوکیشن'), upload_to='hotels/loc/', null=True, blank=True)
    rating = models.DecimalField(verbose_name=_('امتیاز'), max_digits=3, decimal_places=0)
    # TODO: add amenities for hotel
    description = models.TextField(verbose_name=_("توضیحات"))
    active = models.BooleanField(verbose_name=_('فعال/غیرفعال'), default=True)
    keywords = models.TextField(verbose_name=_('کلمات کلیدی'), null=True, blank=True)
    categories = models.ManyToManyField(
        to=TravelCategory,
        related_name='hotel_categories',
        verbose_name=_('categories')

    )

    class Meta:
        verbose_name = 'هتل'
        verbose_name_plural = '2. هتل ها'

    objects = HotelManager()

    def get_min_price(self):
        return self.rooms.first()

    def get_replaced_title(self):
        return self.title.replace(' ', '-')

    def get_absolute_url(self):
        return reverse('travel:hotel-detail', args=[self.id, self.get_replaced_title()])

    def __str__(self):
        return self.title


class Image(models.Model):
    hotel = models.ForeignKey(Hotel, verbose_name=_('هتل'), related_name='hotel_images', on_delete=models.CASCADE,
                              null=True, blank=True)
    tour = models.ForeignKey(to='Tour', verbose_name=_('تور'),
                             related_name='tour_images', on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(verbose_name=_('تصویر'), upload_to='images/')

    def get_thumbnail(self):
        return format_html(f"<img width=100 height=75 style='border-radius: 5px;' src='{self.image.url}'>")

    get_thumbnail.short_description = "تصویر"

    class Meta:
        verbose_name = 'تصویر'
        verbose_name_plural = '4. تصاویر'

    def __str__(self):
        if self.hotel:
            return f"{self.hotel.title} hotel"
        elif self.tour:
            return f"{self.tour.title} tour"
        return "Image"


class HotelRoom(models.Model):
    title = models.CharField(verbose_name=_('عنوان'), max_length=200, null=True, blank=True)
    hotel = models.ForeignKey(Hotel, verbose_name=_('هتل'), related_name='rooms', on_delete=models.CASCADE)
    meal_plan = models.CharField(verbose_name=_('وعده غذایی'), max_length=100)
    price_per_night = models.DecimalField(verbose_name=_('قیمت هر شب'), max_digits=10, decimal_places=0)
    currency = models.CharField(max_length=20, null=True, verbose_name=_('واحد پول'))
    description = models.TextField(verbose_name=_('توضیحات'), null=True, blank=True)
    image = models.ImageField(verbose_name=_('تصویر کاور'), upload_to='hotels/', null=True, blank=True)

    class Meta:
        verbose_name = 'اتاق هتل'
        verbose_name_plural = '2.1 اتاق ها'
        ordering = ('price_per_night',)

    def __str__(self):
        return f"{self.hotel.title} - {self.title}"


class Tour(models.Model):
    image = models.ImageField(verbose_name=_('تصویر'), upload_to='tours/images/')
    title = models.CharField(verbose_name=_('عنوان'), max_length=200)
    summary = models.CharField(verbose_name=_('خلاصه'), max_length=200)
    # ai_summary = models.TextField(verbose_name=_('خلاصه هوش مصنوعی'), null=True, blank=True)
    description = models.TextField(verbose_name=_('توضیحات'))
    # accommodation = models.CharField(verbose_name=_('اقامت'), max_length=200)
    # transport_text = models.CharField(verbose_name=_('حمل و نقل (متن)'), null=True, blank=True, max_length=200)
    # transport_ticket = models.ForeignKey(to='FlightTicket', verbose_name=_('حمل و نقل (بلیط پرواز)'),
    #                                      on_delete=models.SET_NULL,
    #                                      null=True, blank=True)
    # meals = models.CharField(verbose_name=_('وعده های غذایی'), max_length=200)
    start_time = models.DateTimeField(verbose_name=_('زمان شروع'))
    end_time = models.DateTimeField(verbose_name=_('زمان پایان'))
    price_per_person = models.DecimalField(verbose_name=_('قیمت به ازای هر نفر'), max_digits=10, decimal_places=0)
    currency = models.CharField(max_length=20, null=True, verbose_name=_('واحد پول'))
    active = models.BooleanField(verbose_name=_('فعال/غیرفعال'), default=True)
    keywords = models.TextField(verbose_name=_('کلمات کلیدی'), null=True, blank=True)
    categories = models.ManyToManyField(
        to=TravelCategory,
        related_name='tour_categories',
        verbose_name=_('categories')

    )

    class Meta:
        verbose_name = 'تور'
        verbose_name_plural = '3. تور ها'

    objects = TourManager()

    def get_replaced_title(self):
        return self.title.replace(' ', '-')

    def get_absolute_url(self):
        return reverse('travel:tour-detail', args=[self.id, self.get_replaced_title()])

    def __str__(self):
        return self.title


class TourDay(models.Model):
    day = models.CharField(verbose_name=_('روز'), max_length=200)
    summary = models.TextField(verbose_name=_('خلاصه'))
    image = models.ImageField(verbose_name=_('تصویر-Optional'), upload_to='tours/images', null=True, blank=True)
    tour = models.ForeignKey(to='Tour', verbose_name=_('تور'),
                             related_name='tour_days', on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = 'برنامه تور'
        verbose_name_plural = '3.1 برنامه تور ها'

    def __str__(self):
        return f"{self.tour.title} - {self.day}"


class Visa(models.Model):
    title = models.CharField(max_length=255, verbose_name=_('Title'))
    about = models.CharField(max_length=255, verbose_name=_('About'))
    categories = models.ManyToManyField(
        to=TravelCategory,
        related_name='visa_categories',
        verbose_name=_('categories')
    )
    keywords = models.TextField(verbose_name=_('Keywords'), null=True)

    class Meta:
        verbose_name = 'ویزا'
        verbose_name_plural = '6. ویزا'

    def __str__(self):
        return self.title

travel/views.py
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render
from django.views.generic import DetailView

from affiliate_module.models import ProviderLink
from travel.models import Hotel, TravelCategory, Tour, Visa, FlightTicket


# Create your views here.
def hotel_list_view(request):
    hotels = Hotel.objects.filter(active=True)
    categories = TravelCategory.objects.filter(for_hotel=True)

    category = request.GET.get('category')
    if category:
        hotels = Hotel.objects.filter(active=True, categories__name__icontains=category)

    context = {
        'hotels': hotels,
        'categories': categories,
        'category': category,
    }
    return render(request, 'travel/hotel_list.html', context)


class HotelDetailView(DetailView):
    model = Hotel
    template_name = 'travel/hotel_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        hotel = self.object

        hotel_type = ContentType.objects.get_for_model(Hotel)

        provider_links = ProviderLink.objects.filter(
            content_type=hotel_type,
            object_id=hotel.id
        )

        context['provider_links'] = provider_links
        return context


def tour_list_view(request):
    tours = Tour.objects.filter(active=True)
    categories = TravelCategory.objects.filter(for_tour=True)

    category = request.GET.get('category')
    if category:
        tours = Tour.objects.filter(active=True, categories__name__icontains=category)

    context = {
        'tours': tours,
        'categories': categories,
        'category': category,
    }
    return render(request, 'travel/tour_list.html', context)


class TourDetailView(DetailView):
    model = Tour
    template_name = 'travel/tour_detail.html'


def visa_list_view(request):
    visa_type = ContentType.objects.get_for_model(Visa)
    visa_links = ProviderLink.objects.filter(content_type=visa_type)

    context = {
        'visa_links': visa_links,
    }
    return render(request, 'travel/visa_list.html', context)


def flight_list_view(request):
    flight = ContentType.objects.get_for_model(FlightTicket)
    flights = ProviderLink.objects.filter(content_type=flight)

    context = {
        'flights': flights,
    }
    return render(request, 'travel/flight_list.html', context)

travel/templates/travel/hotel_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    DubaiBy | هتل های دبی
{% endblock %}

{% block title_secondary %}
    {% if category %}
        هتل های {{ category }}
    {% else %}
        بهترین هتل های دبی
    {% endif %}
{% endblock %}

{% block main %}
    <!--begin::Wrapper container-->
    <div class="app-container container-xxl">
        <!--begin::اصلی-->
        <div class="app-main flex-column flex-row-fluid" id="kt_app_main">
            <!--begin::Content wrapper-->
            <div class="d-flex flex-column flex-column-fluid">
                <!--begin::Content-->
                <div id="kt_app_content" class="app-content flex-column-fluid">
                    <!--begin::Row-->
                    <div class="row g-5 g-xl-8">
                        <!--begin::Col-->
                        <div class="col-xl-12 ps-xl-12">
                            <div class="row g-5 g-xl-10 mb-5 mb-xl-10">
                                <div class="col-xl-12">
                                    <!--begin::Engage widget 7-->
                                    <div class="card card-flush h-xl-100">
                                        <!--begin::Header-->
                                        <div class="card-header pt-7">
                                            <!--begin::Title-->
                                            <h3 class="card-title align-items-start flex-column">
                                                <span class="card-label fw-bold text-gray-900 fs-2">{% if category %}
                                                    هتل در دسته {{ category }}
                                                {% else %}
                                                    هتل های محبوب هفته
                                                {% endif %}</span>
                                            </h3>
                                            <!--end::Title-->
                                        </div>
                                        <!--end::Header-->
                                        <!--begin::کارت body-->
                                        <div class="card-body pt-7">
                                            <!--begin::Row-->
                                            <div class="row align-items-end h-100 gx-5 gx-xl-10">
                                                {% for hotel in hotels %}
                                                    <!--begin::Col-->
                                                    <div class="col-md-3 mb-11 mb-md-0">
                                                        <!--begin::Overlay-->
                                                        <a class="d-block overlay"
                                                           data-fslightbox="lightbox-hot-sales"
                                                           href="{{ hotel.get_absolute_url }}">
                                                            <!--begin::Image-->
                                                            <div class="overlay-wrapper bgi-position-center bgi-no-repeat bgi-size-cover h-200px card-rounded mb-3"
                                                                 style="height: 266px;background-image:url({{ hotel.image.url }})">
                                                            </div>
                                                            <!--end::Image-->
                                                            <!--begin::Actions-->
                                                            <div
                                                                    class="overlay-layer card-rounded bg-dark bg-opacity-25">
                                                                <i
                                                                        class="ki-outline ki-eye fs-3x text-white"></i>
                                                            </div>
                                                            <!--end::Actions-->
                                                        </a>
                                                        <!--end::Overlay-->
                                                        <!--begin::Info-->
                                                        <div class="m-0">
                                                            <!--begin::Title-->
                                                            <a href="{{ hotel.get_absolute_url }}"
                                                               class="text-gray-800 text-hover-primary fs-3 fw-bold d-block mb-2">{{ hotel.title }}</a>
                                                            <!--end::Title-->
                                                            <!--begin::زمان-->
                                                            <span
                                                                    class="fw-bold fs-6 text-gray-500 d-block lh-1">قیمت:
                                                                        از
                                                                {{ hotel.get_min_price.price_per_night }}{{ hotel.get_min_price.currency }}</span>
                                                            <!--end::زمان-->
                                                        </div>
                                                        <!--end::Info-->
                                                    </div>
                                                    <!--end::Col-->
                                                {% empty %}
                                                    <div class="alert alert-secondary text-dark">
                                                        هتلی یافت نشد
                                                    </div>
                                                {% endfor %}

                                            </div>
                                            <!--end::Row-->
                                        </div>
                                        <!--end::کارت body-->
                                    </div>
                                    <!--end::Engage widget 7-->
                                </div>
                                <!--end::Col-->
                            </div>
                            <div class="row mb-5 mb-xl-8 g-5 g-xl-8">
                                {% for category in categories %}
                                    <!--begin::Col-->
                                    <div class="col-6 col-md-3">
                                        <!--begin::کارت-->
                                        <a class="card flex-column justfiy-content-start align-items-start text-start w-100 text-gray-800 text-hover-primary p-10"
                                           href="{% url 'travel:hotel-list' %}?category={{ category.name }}">
                                            <i
                                                    class="ki-outline ki-abstract-26 fs-2tx mb-5 ms-n1 text-gray-500"></i>
                                            <span class="fs-6 fw-bold">هتل {{ category.name }}</span>
                                        </a>
                                        <!--end::کارت-->
                                    </div>
                                    <!--end::Col-->
                                {% endfor %}

                            </div>
                            <div class="row g-5 g-xl-10 mb-5 mb-xl-10">
                                <!--begin::Col-->
                                <div class="col-xxl-12">
                                    <!--begin::Engage widget 8-->
                                    <div class="card border-0 h-md-100" data-bs-theme="light"
                                         style="background: linear-gradient(112.14deg, #3B2A38 0%, #7a6075 100%)">
                                        <!--begin::Body-->
                                        <div class="card-body">
                                            <!--begin::Row-->
                                            <div class="row align-items-center h-100">
                                                <!--begin::Col-->
                                                <div class="col-7 ps-xl-13">
                                                    <!--begin::Title-->
                                                    <div class="text-white mb-6 pt-6">
                                                                    <span class="fs-2 fw-bold">طراحی هوشمند پلن
                                                                        سفر</span>
                                                    </div>
                                                    <!--end::Title-->
                                                    <!--begin::Text-->
                                                    <span
                                                            class="fw-semibold text-white fs-6 mb-8 d-block opacity-75">برنامه
                                                                    سفرت رو با DubaiBy هوشمند و ویژه بچین</span>
                                                    <!--end::Text-->
                                                    <!--begin::Actions-->
                                                    <div
                                                            class="d-flex flex-column flex-sm-row d-grid gap-2">
                                                        <a href="#"
                                                           class="btn btn-facebook flex-shrink-0 me-lg-2"
                                                           data-bs-toggle="modal"
                                                           data-bs-target="#kt_modal_upgrade_plan">برنامه
                                                            سفرتو بچین</a>
                                                        <a href="#" class="btn btn-primary flex-shrink-0"
                                                           style="background: rgba(255, 255, 255, 0.2)"
                                                           data-bs-toggle="modal"
                                                           data-bs-target="#kt_modal_create_app">از دستیار
                                                            هوشمندت بپرس</a>
                                                    </div>
                                                    <!--end::Actions-->
                                                </div>
                                                <!--end::Col-->
                                                <!--begin::Col-->
                                                <div class="col-5 pt-10">
                                                    <!--begin::Illustration-->
                                                    <div class="bgi-no-repeat bgi-size-contain bgi-position-x-end h-225px"
                                                         style="background-image:url({% static 'site/medias/svg/illustrations/easy/5.svg' %})">
                                                    </div>
                                                    <!--end::Illustration-->
                                                </div>
                                                <!--end::Col-->
                                            </div>
                                            <!--end::Row-->
                                        </div>
                                        <!--end::Body-->
                                    </div>
                                    <!--end::Engage widget 8-->
                                </div>
                                <!--end::Col-->
                            </div>
                        </div>
                    </div>
                    <!--end::Row-->
                </div>
                <!--end::Content-->
            </div>
            <!--end::Content wrapper-->
            <!--begin::Footer-->
            <div id="kt_app_footer"
                 class="app-footer d-flex flex-column flex-md-row align-items-center flex-center flex-md-stack py-2 py-lg-4">
                <!--begin::کپیright-->
                <div class="text-gray-900 order-2 order-md-1">
                    <span class="text-muted fw-semibold me-1">2024&copy;</span>
                    <a href="https://keenthemes.com" target="_blank"
                       class="text-gray-800 text-hover-primary">ساتراس وب</a>
                </div>
                <!--end::کپیright-->
                <!--begin::Menu-->
                <ul class="menu menu-gray-600 menu-hover-primary fw-semibold order-1">
                    <li class="menu-item">
                        <a href="https://keenthemes.com" target="_blank" class="menu-link px-2">درباره ی
                            ما</a>
                    </li>
                    <li class="menu-item">
                        <a href="https://rtl-theme.com" target="_blank" class="menu-link px-2">پشتیبانی</a>
                    </li>
                    <li class="menu-item">
                        <a href="https://www.rtl-theme.com/metronic-admin-html-template/" target="_blank"
                           class="menu-link px-2">خرید</a>
                    </li>
                </ul>
                <!--end::Menu-->
            </div>
            <!--end::Footer-->
        </div>
        <!--end:::اصلی-->
    </div>
    <!--end::Wrapper container-->
{% endblock %}